name: Ouput Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: Install dependencies
        uses: actions/checkout@v3
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt

      - name: Testing
        uses: actions/checkout@v3
      - run: echo "Testing"
      - run: python3 app.py tests/example_task.json output.yml
      - run: cat output.yml
      - run: echo "Complete"

